name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for mkdocs-git-revision-date-localized-plugin
      # https://github.com/marketplace/actions/setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -r library.txt
      - run: mkdocs gh-deploy --force
